from setuptools import setup, find_packages

setup(
    name='auto_code_rover',
    version='0.1.0',
    author='Your Name',
    author_email='your-email@example.com',
    description='A project description here',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/your-username/your-repo',
    packages=find_packages(),
    python_requires='>=3.10',
    install_requires=[
        'loguru==0.7.2',
        'requests>=2.31.0',
        'rich==13.7.1',
        'annotated-types==0.6.0',
        'anyio==4.2.0',
        'beautifulsoup4==4.12.3',
        'boto3==1.34.122',
        'certifi==2023.11.17',
        'distro==1.9.0',
        'docstring-parser==0.15',
        'h11==0.14.0',
        'httpcore==1.0.2',
        'httpx==0.27.0',
        'idna==3.6',
        'lxml==5.1.0',
        'openai>=1.30.0',
        'pydantic==2.5.3',
        'pydantic-core==2.14.6',
        'python-dotenv==1.0.0',
        'sniffio==1.3.0',
        'soupsieve==2.5',
        'tenacity>=8.4.2',
        'termcolor==2.4.0',
        'timeout-decorator==0.5.0',
        'tqdm==4.66.3',
        'typing-extensions==4.9.0',
        'unittest-xml-reporting==3.2.0',
        'coverage==7.4.4',
        'pylint==3.1.0',
        'litellm==1.35.20',
        'ollama==0.1.8',
        'flask==3.0.3',
        'flask_cors==4.0.0',
        'unidiff==0.7.5'
    ],
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    entry_points={
        'console_scripts': [
            'your-script=your_module:main_function',
        ],
    },
)
